### PR TITLE
[bugfix] event duration nil handle case

### PR DESCRIPTION
**Pull request by ajaystha42**
Addresses: https://github.com/restarone/violet_rails/issues/1436
Demo: 

https://user-images.githubusercontent.com/55496123/224464889-cac31dd2-4eea-4baa-8454-46f86ca96eea.mov

### CODE REVIEW

**Comment by donrestarone** [comment]
⚠️ with @ajaystha42 's hot fix in place, I'm doing a one-off [deployment](https://github.com/restarone/violet_rails/actions/runs/4390358438/jobs/7693360333) to [nikean.org](https://github.com/restarone/violet_rails/settings/environments/447769648/edit)

**Comment by donrestarone** [comment]
@ajaystha42 the issue still persists. The exception is raised further long in the stack now: 

``` txt
An ActionView::Template::Error occurred in dashboard#dashboard:

  nil can't be coerced into Float
  app/helpers/dashboard_helper.rb:90:in `avg_view_percentage'


-------------------------------
Request:
-------------------------------

  * URL        : https://nikean.org/v2/dashboard
  * HTTP Method: GET
  * IP address : 184.151.190.151
  * Parameters : {"controller"=>"comfy/admin/v2/dashboard", "action"=>"dashboard"}
  * Timestamp  : 2023-03-11 16:38:35 UTC
  * Server : ip-172-31-14-250
    * Rails root : /var/www/violet/releases/20230311162625
  * Process: 140681

```

**Comment by ajaystha42** [comment]
> @ajaystha42 the issue still persists. The exception is raised further long in the stack now:
> 
> ```
> An ActionView::Template::Error occurred in dashboard#dashboard:
> 
>   nil can't be coerced into Float
>   app/helpers/dashboard_helper.rb:90:in `avg_view_percentage'
> 
> 
> -------------------------------
> Request:
> -------------------------------
> 
>   * URL        : https://nikean.org/v2/dashboard
>   * HTTP Method: GET
>   * IP address : 184.151.190.151
>   * Parameters : {"controller"=>"comfy/admin/v2/dashboard", "action"=>"dashboard"}
>   * Timestamp  : 2023-03-11 16:38:35 UTC
>   * Server : ip-172-31-14-250
>     * Rails root : /var/www/violet/releases/20230311162625
>   * Process: 140681
> ```

@donrestarone  The already existing total_duration with null value was causing the issue. I fixed it in the latest commit. Please have a look

**Comment by donrestarone** [comment]
⚠️  @ajaystha42  with the new commit, I am [deploying](https://github.com/restarone/violet_rails/actions/runs/4390358438/jobs/7702424549) to [nikean.org](https://github.com/restarone/violet_rails/settings/environments/447769648/edit)

**Comment by ajaystha42** [comment]
> ⚠️ @ajaystha42 with the new commit, I am [deploying](https://github.com/restarone/violet_rails/actions/runs/4390358438/jobs/7702424549) to [nikean.org](https://github.com/restarone/violet_rails/settings/environments/447769648/edit)
> 
> EDIT, same issue. Need fresh eyes

@donrestarone  can you please share the data for this query? `Ahoy::Event.where("properties ->> 'total_duration' IS NULL").jsonb_search(:properties, { category: "video_view" })`

**Comment by ajaystha42** [comment]
@donrestarone  please deploy to nikean.org. I made few changes in the latest commit

**Comment by donrestarone** [comment]
@ajaystha42 can't deploy due to CI failure

**Comment by donrestarone** [comment]
⚠️ temporary [deployment](https://github.com/restarone/violet_rails/actions/runs/4407866007/jobs/7740444849) to [nikean.org](https://github.com/restarone/violet_rails/settings/environments/447769648/edit)

**Pull request closed without merging**
