### PR TITLE
[bugfix] api resource undefined method error

### PR DESCRIPTION
**Pull request by ajaystha42**
Addresses: https://github.com/restarone/violet_rails/issues/1357
Demo: 

https://user-images.githubusercontent.com/55496123/213843605-9ad48e47-2469-4b53-a182-7146f1331f3d.mov

### CODE REVIEW

**Comment by donrestarone** [comment]
The data that was submitted when the error happened (recaptcha failure, etc) was not included in the email when the client engineer has specified the data be included: 

Screen Shot 2023-01-18 at 2 19 02 PM


IMG_1260

**Comment by donrestarone** [comment]
re-deploying master to Nikean: https://github.com/restarone/violet_rails/actions/runs/3934979420/jobs/6766925907

**Comment by ajaystha42** [comment]
@donrestarone  can you please send me the api actions for the tested id using rails console?

**Comment by donrestarone** [comment]
@ajaystha42 as mentioned [here](https://github.com/restarone/violet_rails/pull/1359#issuecomment-1387634135), its in [this comment](https://github.com/restarone/violet_rails/issues/1357#issuecomment-1385550859)

**Comment by ajaystha42** [comment]
> @ajaystha42 as mentioned [here](https://github.com/restarone/violet_rails/pull/1359#issuecomment-1387634135), its in [this comment](https://github.com/restarone/violet_rails/issues/1357#issuecomment-1385550859)

@donrestarone , no i meant by using id after deploying the bugfix code to nikean

**Comment by donrestarone** [comment]
⚠️  running temporary deployment to nikean.org to validate patch: https://github.com/restarone/violet_rails/actions/runs/3976044989/jobs/6817361868

**Pull request merged**
