### PR TITLE
[feature] Prevent raw SQL usage in API (#1220)

### PR DESCRIPTION
**Pull request by donrestarone**
Addresses: https://github.com/restarone/violet_rails/issues/1144

Co-authored-by: Prashant <alish.khadka@gmail.com>

### CODE REVIEW

**Comment by donrestarone** [comment]
⚠️  after deployment `UniqueStringAggregator` and `VacuumJob` both need to be updated with the code in test/fixtures/external_api_clients.yml

**Comment by donrestarone** [comment]
we expect errors like this after deployment: 

``` txt

Validation failed: Model definition contains disallowed keyword: ["ActiveRecord::Base"]. Please refactor model_definition accordingly
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/validations.rb:80:in `raise_validation_error'

-------------------------------
Backtrace:
-------------------------------

  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/validations.rb:80:in `raise_validation_error'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/validations.rb:53:in `save!'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/transactions.rb:302:in `block in save!'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:318:in `transaction'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/transactions.rb:302:in `save!'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/suppressor.rb:48:in `save!'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/persistence.rb:639:in `block in update!'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/transactions.rb:354:in `block in with_transaction_returning_status'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `block in transaction'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/transaction.rb:319:in `block in within_new_transaction'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:26:in `block (2 levels) in synchronize'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `handle_interrupt'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:25:in `block in synchronize'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `handle_interrupt'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.5/lib/active_support/concurrency/load_interlock_aware_monitor.rb:21:in `synchronize'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/transaction.rb:317:in `within_new_transaction'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/connection_adapters/abstract/database_statements.rb:320:in `transaction'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/transactions.rb:350:in `with_transaction_returning_status'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activerecord-6.1.5/lib/active_record/persistence.rb:637:in `update!'
  /var/www/violet/releases/20221112132014/app/sidekiq/external_api_client_job.rb:17:in `rescue in perform'
  /var/www/violet/releases/20221112132014/app/sidekiq/external_api_client_job.rb:10:in `perform'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:196:in `execute_job'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:164:in `block (2 levels) in process'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:138:in `block in invoke'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/ros-apartment-sidekiq-1.2.0/lib/apartment/sidekiq/middleware/server.rb:5:in `block in call'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/ros-apartment-2.9.0/lib/apartment/adapters/abstract_adapter.rb:89:in `switch'
  /home/ubuntu/.rbenv/versions/2.6.6/lib/ruby/2.6.0/forwardable.rb:230:in `switch'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/ros-apartment-sidekiq-1.2.0/lib/apartment/sidekiq/middleware/server.rb:4:in `call'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:140:in `block in invoke'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/middleware/chain.rb:143:in `invoke'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:163:in `block in process'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/job_retry.rb:114:in `local'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/rails.rb:14:in `block in call'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.5/lib/active_support/execution_wrapper.rb:91:in `wrap'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.5/lib/active_support/reloader.rb:72:in `block in wrap'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.5/lib/active_support/execution_wrapper.rb:91:in `wrap'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/activesupport-6.1.5/lib/active_support/reloader.rb:71:in `wrap'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/rails.rb:13:in `call'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:257:in `stats'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/job_logger.rb:13:in `call'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/job_retry.rb:81:in `global'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:124:in `block in dispatch'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/job_logger.rb:39:in `prepare'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:123:in `dispatch'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:162:in `process'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:78:in `process_one'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/processor.rb:68:in `run'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/util.rb:56:in `watchdog'
  /var/www/violet/shared/bundle/ruby/2.6.0/gems/sidekiq-6.4.1/lib/sidekiq/util.rb:65:in `block in safe_thread'

-------------------------------
Data:
-------------------------------

  * data: {:sidekiq=>
    {:context=>"Job raised exception",
     :job=>
      {"retry"=>true,
       "queue"=>"default",
       "args"=>[5],
       "class"=>"ExternalApiClientJob",
       "jid"=>"57cf01b13985ea4c6e3199e3",
       "created_at"=>1668259924.9814715,
       "apartment"=>"support",
       "enqueued_at"=>1668260016.8802454,
       "error_message"=>
        "Validation failed: Model definition contains disallowed keyword: [\"ActiveRecord::Base\"]. Please refactor model_definition accordingly",
       "error_class"=>"ActiveRecord::RecordInvalid",
       "failed_at"=>1668259925.0061483,
       "retry_count"=>2,
       "retried_at"=>1668259980.2103794},
     :jobstr=>
      "{\"retry\":true,\"queue\":\"default\",\"args\":[5],\"class\":\"ExternalApiClientJob\",\"jid\":\"57cf01b13985ea4c6e3199e3\",\"created_at\":1668259924.9814715,\"apartment\":\"support\",\"enqueued_at\":1668260016.8802454,\"error_message\":\"Validation failed: Model definition contains disallowed keyword: [\\\"ActiveRecord::Base\\\"]. Please refactor model_definition accordingly\",\"error_class\":\"ActiveRecord::RecordInvalid\",\"failed_at\":1668259925.0061483,\"retry_count\":2,\"retried_at\":1668259980.2103794}"}}
```

the fix is to call `ApiResource` for transactions instead of `Activerecord::Base`

**Comment by donrestarone** [comment]
@Ayon95 can you check and confirm if I listed every instance of `VacuumJob` and `UniqueStringAggregator` [here](https://github.com/restarone/violet_rails/pull/1222#issuecomment-1312476833)?

**Comment by Ayon95** [comment]
@donrestarone  Okay I'll check. Can you give me access to Nikean API?

**Comment by Ayon95** [comment]
Yeah the ones listed are all the instances of `VacuumJob` and `UniqueStringAggregator` being used in production.

**Pull request merged**
