### PR TITLE
API namespaces list view

### PR DESCRIPTION
**Pull request by Ayon95**
Addresses: #1503 

## Before

Screen Shot 2023-04-11 at 11 52 53 AM

## After

https://user-images.githubusercontent.com/73725297/230971387-635f4744-4acb-46f7-a056-12a1541a4351.mp4

### CODE REVIEW

**Comment by donrestarone** [comment]
## 🧪 UAT feedback


Please see below, 

1. The grid should take the full height of the viewport
2. the label and categorizations should co-exist better. Consider left justifying the labels, and having the categorizations on its own line. So the user is presented with a consistent click point for each of the API Namespaces in the list
Screen Shot 2023-04-06 at 5 25 10 PM
Screen Shot 2023-04-06 at 5 14 53 PM

**Comment by Ayon95** [comment]
Should the categories have a separate column?

**Comment by donrestarone** [comment]
code LGTM, but the lack of test failures / tests is concerning.  @Ayon95 could you check if this area of the code is covered? If not, you'll need to add a few tests exercising the search, sort columns etc: 

Screen Shot 2023-04-06 at 5 34 11 PM

**Comment by donrestarone** [comment]
@Ayon95 bringing this issue back to you, 
Screen Shot 2023-04-10 at 8 18 30 AM

**Review by donrestarone — APPROVED** [review]
code LGTM

**Pull request merged**
