### PR TITLE
[feature] permissioned forum access

### PR DESCRIPTION
**Pull request by alis-khadka**
Addresses: https://github.com/restarone/violet_rails/issues/1305

**Demo**

https://user-images.githubusercontent.com/25191509/210078509-2b229519-0028-4b4a-8c59-7f5c9d2d137f.mov

### CODE REVIEW

**Comment by donrestarone** [comment]
Acceptance criteria: 

1. When forum is public, visitors should have read access  ⌛ 
2. When forum is public, users without access permission should have read access ⌛ 
3. When forum is public, users with access permission should have write access ⌛ 
4. When forum is private, users without access permission should not have read access ⌛ 
5. When forum is private, users with access permission should have read/write access ⌛ 
6. Users with moderator permission should have ability to access forum categories ⌛ 
7. Users with moderator permission should have ability to modify any post/thread ⌛

**Comment by donrestarone** [comment]
@alis-khadka to fix the PR so it adheres to [this](https://github.com/restarone/violet_rails/pull/1325#issuecomment-1368517983)

**Comment by alis-khadka** [comment]
@donrestarone 

1. When forum is `public`, should we restrict the visitors and users without access permission from creating forum thread/post ?
2. Should we allow only users with moderator permission, to create new `forum categories`?
3. And, users with moderator permission will bypass the access permission, right?

**Comment by donrestarone** [comment]
@alis-khadka `can manage forum supersedes `can access forum` so when `can manage forum` is checked, we should auto check the `can access forum` checkbox to indicate it to the user

Screen Shot 2023-01-05 at 10 09 18 AM

**Pull request merged**
