### PR TITLE
[bug fix] Run Error API actions

### PR DESCRIPTION
**Pull request by donrestarone**
Addresses: https://github.com/restarone/violet_rails/issues/985

Addresses: https://github.com/restarone/violet_rails/issues/1071

### Demo:

https://user-images.githubusercontent.com/50227291/188673867-186d03e9-a8ec-4cb7-adb0-6a6483ba1cec.mov

Since api resource is not saved due to any error, api action will keep track of user input with proper error message under 

`additional_data['api_resource']['properties']` and `additional_data['api_resource']['errors']`

Demo shows error message and user input being accessed by api_action

### Demo fix dead set functionality

https://user-images.githubusercontent.com/50227291/189976658-e7c6fbe8-1f69-4740-9e98-98835a8fae26.mov

### Demo showing error message in API 
https://user-images.githubusercontent.com/50227291/196223270-e1d831f3-8403-43eb-84c2-d5419ea078d4.mov

### CODE REVIEW

**Comment by donrestarone** [comment]
@Pralish opening a base branch on the repo for you,

im adding the unsafe label until we figure out how to [fix your discovery here](https://github.com/restarone/violet_rails/pull/1086#issuecomment-1251872282)

**Comment by donrestarone** [comment]
@Pralish we forgot to talk about this task today, what are the next steps here?

**Comment by donrestarone** [comment]
@Pralish I merged the branch you linked and there is a CI failure

**Comment by Pralish** [comment]
> @Pralish I merged the branch you linked and there is a CI failure

Fixed

**Comment by donrestarone** [comment]
@Pralish i re ran some failed API actions and got this error for a few of them. Can you take a look? https://review-1125.violet-test.net/api_namespaces/25/api_actions/1105

**Comment by donrestarone** [comment]
any updates on this @Pralish @alis-khadka ? I'm looking to have this shipped hopefully this week

**Comment by Pralish** [comment]
@donrestarone , this is ready for UAT

**Comment by donrestarone** [comment]
@Pralish I tested this by having a custom API action raise an error, 

1. I see the retry in the sidekiq UI (under retries and dead)
2. the state in Violet Actions is `executing`.  Should this be in the `failed` state instead? 



Screen Shot 2022-12-22 at 8 36 34 AM
Screen Shot 2022-12-22 at 8 33 23 AM

**Comment by Pralish** [comment]
@donrestarone , I just checked the same api action. It's now in failed state. Did you make any change?

Also, The api action's state will only change to failed state after all retries are exhausted, ie. after 3rd retry.  Do you want me to change this behavior? 

Screenshot 2022-12-22 at 10 16 37 PM

**Pull request merged**
