### PR TITLE
[bug fix] non renderable API Namespace unable to create Resources

### PR DESCRIPTION
**Pull request by ajaystha42**
Addresses: https://github.com/restarone/violet_rails/issues/1111

If has_form is unchecked, 

Screen Shot 2023-01-12 at 8 42 02 PM

then the form is not rendered

Screen Shot 2023-01-13 at 2 43 15 PM

### CODE REVIEW

**Comment by donrestarone** [comment]
is this ready for review?

**Comment by ajaystha42** [comment]
yes @donrestarone , its ready for review

**Comment by donrestarone** [comment]
@ajaystha42 moving forward, please attach dev proofs with PR's. Screenshots/video are required to be included in the release.

**Comment by donrestarone** [comment]
@ajaystha42  this is passing UAT ✅  before merge, please Rename "Has Form" to "Renderable (Form, and representation)"

**Comment by ajaystha42** [comment]
@donrestarone  done

**Comment by donrestarone** [comment]
@ajaystha42 I didn't mean the title, I meant in the application code

**Comment by ajaystha42** [comment]
you mean here? @donrestarone 
Screenshot 2023-01-13 at 14 58 12

**Comment by ajaystha42** [comment]
@donrestarone  please check the changes

**Comment by donrestarone** [comment]
@ajaystha42 you're missing tests. There should be at least 1 test that fails without your patch in place.

**Comment by KripanandaZebec** [comment]
Acceptance Criteria: 

- User must be able to create API Resource Even if the Has form(Renderable) box is ticked or checked.
- User must be able to create API Resource Even if the Has form(Renderable) box is not ticked or checked.

**Comment by kripananda-yadav** [comment]
Acceptance Criteria:

User must be able to create API Resource Even if the Has form(Renderable) box is ticked or checked.
User must be able to create API Resource Even if the Has form(Renderable) box is not ticked or checked.

**Comment by kripananda-yadav** [comment]
Acceptance Criteria:

User must be able to create API Resource Even if the Has form(Renderable) box is ticked or checked.
User must be able to create API Resource Even if the Has form(Renderable) box is not ticked or checked.

**Comment by donrestarone** [comment]
@kripananda-yadav this does not require UAT. as indicated by me adding the passing UAT on Testnet ✅ label a few days ago (well before your comment [here](https://github.com/restarone/violet_rails/pull/1354#issuecomment-1386495601))

**Pull request merged**
