### PR TITLE
[feature] allow access to API by category (#1103)

### PR DESCRIPTION
**Pull request by donrestarone**
Addresses: https://github.com/restarone/violet_rails/issues/1075

# Demo

https://user-images.githubusercontent.com/35935196/191496793-30d7e50f-7674-489f-bb30-699fa4ab02f6.mp4

https://user-images.githubusercontent.com/25191509/198866316-2d57a2de-2e33-42ab-ba74-c59eb59c08c0.mov

### CODE REVIEW

**Comment by donrestarone** [comment]
@alis-khadka just created a base branch for you and deployed a review app 🥇

**Comment by donrestarone** [comment]
@alis-khadka please see below for feedback:

1. ❌  when navigating to the screen below, fields are rendered as unchecked (even if enabled on the backend) causing a bad write when the user submits the form without changing anything 

Screen Shot 2022-10-27 at 6 04 37 PM

2. add permissions for delete access on API resource and API Namespace  
Screen Shot 2022-10-27 at 6 13 36 PM

**Comment by donrestarone** [comment]
@alis-khadka can you fix the merge conflicts?

**Comment by alis-khadka** [comment]
> @alis-khadka can you fix the merge conflicts?

Sure, will do it.

**Reminder**

After the following PR gets merged related to webhook strategy, we will need to refactor the access for ApiKeys as well.
https://github.com/restarone/violet_rails/pull/1167

**Comment by alis-khadka** [comment]
@donrestarone The code conflict has been resolved.

Since, there is a separate tab for social sharing meta. Do we need to add specific access for this as well like we did for the export feature of namespace?
Screen Shot 2022-11-14 at 15 22 55

**Comment by kripananda-yadav** [comment]
User should be redirected to the proper page when user tries to access any page related to the API submenu.
Like Homepage/starting page/page not found page.
For eg Page that lies under API section https://review-1181.violet-test.net/api_namespaces but the user 
who is trying to access the page do not have the permission to view the content of the page then the user 
must be redirected to the proper landing page https://review-1181.violet-test.net/


### ALL NAMESPACE 

FUll ACCESS - ALL the check box on the ALL Namespaces section must be selected and user must be able to perform 
all possible actions like read/edit/delete actions on API Submenu.

FUll READ ACCESS - When User selects Full read access check box and user must be able to
read all the content on API Submenu.

FUll ACCESS FOR API NAMESPACE ONLY - When User selects FUll ACCESS FOR API NAMESPACE ONLY check box and user must be able to
able to Create/Read/Write/delete and API Namespace.


FUll ACCESS FOR API NAMESPACE ONLY - When User selects FUll ACCESS FOR API NAMESPACE ONLY check box and user must be able to
able to Create/Read/Write/delete and API Namespace.

DELTE ACCESS FOR API NAMESPACE ONLY - When User selects DELTE ACCESS FOR API NAMESPACE ONLY check box and user must be able to
able to Delete and API Namespace.

ALLOW EXPORTS - When User selects ALLOW EXPORTS check box and FULL READ ACCESS check box must be selected automatically as well
user must be able to export API Namespace.

ALLOW DUPLICATION - When User selects ALLOW EXPORTS check box then the FULL READ ACCESS check box must be selected automatically as well
user must be able to Duplicate API Namespace.

READ API RESOURCES ONLY - When User selects READ API RESOURCES ONLY check box then the FULL READ ACCESS check box must be selected automatically and 
user must be able to read all API resources.

DELETE ACCESS API RESOURCES ONLY - When User selects DELETE ACCESS API RESOURCES ONLY check box then the FULL READ ACCESS check box must be selected automatically and 
user must be able to Delete all API resources.

FULL ACCESS API RESOURCES ONLY - When User selects FULL ACCESS API RESOURCES ONLY check box then the FULL READ ACCESS check box must be selected automatically and 
user must be able to READ/Delete/EDIT all API resources.


READ API ACTIONS ONLY - When User selects READ API ACTIONS ONLY check box then the FULL READ ACCESS check box must be selected automatically and 
user must be able to READ all API actions.


FULL ACCESS FOR API ACTIONS ONLY - When User selects FULL ACCESS API RESOURCES ONLY check box then the FULL READ ACCESS check box must be selected automatically and 
user must be able to Read/Delete/EDIT all API resources.


READ EXTERNAL API CONNECTIONS ONLY - When User selects READ EXTERNAL API CONNECTIONS ONLY check box then the FULL READ ACCESS check box must be selected automatically and 
user must be able to READ EXTERNAL API CONNECTIONS.

FULL ACCESS FOR EXTERNAL API CONNECTIONS ONLY - When User selects READ EXTERNAL API CONNECTIONS ONLY check box then the FULL READ ACCESS check box must be selected automatically and 
user must be able to READ/EDIT/DELETE EXTERNAL API CONNECTIONS.

READ API CLIENTS ONLY- When User selects READ API CLIENTS ONLY check box then the FULL READ ACCESS check box must be selected automatically and 
user must be able to READ API Clients.


FULL ACCESS FOR API CLIENTS ONLY- When User selects FULL ACCESS FOR API CLIENTS ONLY check box then the FULL READ ACCESS check box must be selected automatically and 
user must be able to READ/EDIT/DELETE API Clients.

FULL ACCESS FOR API FORM ONLY- When User selects FULL ACCESS FOR API FORM ONLY check box then the FULL READ ACCESS check box must be selected automatically and 
user must be able to READ/EDIT/DELETE API FORM.


 




**### ACCEPTANCE CRITERIA** 



### API NAMESPACES BY CATEGORY

WHEN user selects any category only the content/namespaces related to that category should be displayed and User must only be able to perform actions which HE/SHE has been given permissions of.

Permission for user in API NAMESPACE BY CATEGROY are same as ALL NAMESPACE only difference is in ALL NAMESPACE permission is given for whole API NAMESPACE but in the API NAMESPACE BY CATEGORY Permission is given to a particular Namespaces.

**Comment by kripananda-yadav** [comment]
User should be redirected to the proper page when user tries to access any page related to the API submenu.
Like Homepage/starting page/page not found page. ❌
For eg Page that lies under API section https://review-1181.violet-test.net/api_namespaces but the user
who is trying to access the page do not have the permission to view the content of the page then the user
must be redirected to the proper landing page https://review-1181.violet-test.net/


https://user-images.githubusercontent.com/70195786/202888956-659fbae8-9c39-49ee-8667-0badc4429a2b.mp4

Expected:

User should be taken to the proper page when He?She do not have permission to visit that page which user is requesting.

**Comment by kripananda-yadav** [comment]
DELTE ACCESS FOR API NAMESPACE ONLY - When User selects DELTE ACCESS FOR API NAMESPACE ONLY check box and user must be able to able to Delete and API Namespace. ❌

https://user-images.githubusercontent.com/70195786/202889139-0748089f-ee4c-4e2d-8b6f-b0bc5257352f.mp4

No read access provided to the user when user Ticks DELTE ACCESS FOR API NAMESPACE ONLY check box. Due to which user is not able to perform Delete action

Expected:
User must be provided with read access of Namespace for deleting any desired Namespace

**Comment by kripananda-yadav** [comment]
WHEN user selects any category only the content/namespaces related to that category should be displayed and User must only be able to perform actions which HE/SHE has been given permissions of. ❌

https://user-images.githubusercontent.com/70195786/202889337-ac0add2a-f499-4169-9042-78588f50fd24.mp4

All the namespace are displayed even if the user has permission to view the selected category only.

Expected
When user selects any category then in the API page the content of that category should only be displayed.

**Comment by alis-khadka** [comment]
> @donrestarone The code conflict has been resolved.
> 
> Since, there is a separate tab for social sharing meta. Do we need to add specific access for this as well like we did for the export feature of namespace? Screen Shot 2022-11-14 at 15 22 55

@donrestarone  The form for `Social Share Mapping` and `Action Workflow` are hitting the api_namespaces_controller#update action.

For `Social Share Mapping`, should we refactor it into a separate action and give it a specific access?

For `Action Workflow` form, it seems to be an issue to me because if a user has `full_access_for_api_action`, the user is allowed to visit the action workflow's page but won't be able to submit it. Shall I also refactor it into a separate controller's action?

We can discuss it in a call for further clarification if needed.

**Comment by donrestarone** [comment]
@alis-khadka when the user has the following permissions: 
Screen Shot 2022-11-23 at 9 11 14 PM

they can still read API resource data from the HTML table: 
Screen Shot 2022-11-23 at 9 10 47 PM

That should not be the case, since they don't have the permission `read API Resources`

**Comment by alis-khadka** [comment]
> @alis-khadka when the user has the following permissions: Screen Shot 2022-11-23 at 9 11 14 PM
> 
> they can still read API resource data from the HTML table: Screen Shot 2022-11-23 at 9 10 47 PM
> 
> That should not be the case, since they don't have the permission `read API Resources`

@donrestarone I have addressed this part.

@kripananda-yadav I have addressed your provided feedbacks. It's ready for you to review.

**Comment by kripananda-yadav** [comment]
https://user-images.githubusercontent.com/70195786/205496387-2cd16093-e0c4-4dbb-a757-9e71f7352424.mov
 
In the Full access for External API Connections only user is able to delete any API connections but the validation message is still displayed. 
Which should not be the case instead of the validation message success message should be displayed saying successfully deleted API connections or something like that which maintains the consistency of the system.
@alis-khadka

**Comment by kripananda-yadav** [comment]
https://user-images.githubusercontent.com/70195786/205503936-6432e567-2f21-42dd-8647-ae9f4ddc4897.mov


Discard failed action and rerun failed action are not allowed in the full access api actions.
Discard Failed actions and Rerun failed actions should be allowed on the Full API actions only.

**Comment by kripananda-yadav** [comment]
https://user-images.githubusercontent.com/70195786/205504058-7ad72a79-4eeb-4b4d-8922-a7fe6c3a4563.mov

When user clicks on delete button of the setting menu, user is redirected to a unexpected page instead of showing a message that user don't have permission or any appropriate message.

**Comment by kripananda-yadav** [comment]
@alis-khadka couple of issue has been raised please let me know after the completion.

**Comment by alis-khadka** [comment]
> @alis-khadka couple of issue has been raised please let me know after the completion.

@kripananda-yadav It's ready for you to review.

**Pull request merged**
