### PR TITLE
[feature] Dynamic attributes in API Actions

### PR DESCRIPTION
**Pull request by Pralish**
addresses: https://github.com/restarone/violet_rails/issues/653

addresses: https://github.com/restarone/violet_rails/issues/652

upgrade path: https://github.com/restarone/violet_rails/issues/836

# Feature Showcase

## Dynamic Emails
Given a simple form like this: 
Screenshot from 2022-07-03 14-27-25

an email like this is triggered: 
Screenshot from 2022-07-03 14-24-27

the system will generate the email message: 
Screenshot from 2022-07-03 14-25-07

### CODE REVIEW

**Comment by donrestarone** [comment]
@Pralish as discussed this morning, to drive our framework forward -- we will be deprecating the magic `self.custom_attribute` syntax in favour of plain and explicit ruby (eg: `api_resource.properties["custom_attribute"]` as you are proposing with this PR. 

Please include a migration guide titled "migrating from Data Pipeline V2 to V3" alongside your PR. 

This is an exciting change, but lets make sure our clients don't experience down-time due to it.

**Comment by donrestarone** [comment]
@Pralish before deploying this to staging, just confirming that we can support the following use case? 

Screenshot from 2022-06-21 21-34-28

**Comment by Pralish** [comment]
@donrestarone , Email address field doesn't support string interpolation. Shall I add that as well?

**Comment by donrestarone** [comment]
@Pralish yes please!

**Comment by Pralish** [comment]
@donrestarone , Done

**Comment by donrestarone** [comment]
@Pralish What are we missing to get this on prod? IIRC, we still need a migration guide ("migrating from Data Pipeline V2 to V3")

**Comment by donrestarone** [comment]
Test strategy: 

We will need to test at least 2 API namespaces to be sure that this change does not have any unintended consequences. 

##  sipshucksip.com

1. download API Namespace from https://sipshucksip.com/ that syncs data to ODIN CRM
2. load the API Namespace to our Heroku staging app
3. Submit the form and see what automation breaks 
4. Upgrade the HTTP action to the new syntax
5. Test again to see if the connection between Violet Rails and ODIN CRM work as expected 

## nikean.org

1. download API Namespace from https://nikean.org that syncs data to Mailchimp
2. load the API Namespace to our Heroku staging app
3. remove production API keys and point it to our test Mailchimp account
4. Submit the form and see what automation breaks

**Comment by donrestarone** [comment]
@Pralish there may be some underlying issues we have to address. Lets talk about this during our weekly staff eng call. I have created a thread in [our forum](https://violet.restarone.solutions/forum/threads/sipshucksip-com-people-data-pipeline-broken)

Screen Shot 2022-07-02 at 1 06 41 PM
Screen Shot 2022-07-02 at 1 02 43 PM

**Pull request merged**
