### PR TITLE
[feature] Entity specific analytics

### PR DESCRIPTION
**Pull request by donrestarone**
Addresses: https://github.com/restarone/violet_rails/issues/1292 Screen Shot 2023-01-04 at 8 07 53 AM

Co-authored-by: Pralish Kayastha <50227291+Pralish@users.noreply.github.com>
Co-authored-by: Pralish Kayastha <pralishkayastha@gmail.com>

### CODE REVIEW

**Comment by donrestarone** [comment]
⚠️  @Pralish this is failing UAT on staging due to the following: 

1. Clickable tracking not working:
Screen Shot 2023-01-30 at 12 01 24 AM

2.  Viewable tracking not working:

Screen Shot 2023-01-29 at 11 59 38 PM


In both cases I have ensured that I have consented to cookies/tracking

**Comment by donrestarone** [comment]
On first load, tracking reliability issue is solved by upgrading to the newer cookie consent buttons instead of anchor links: 

use this
``` html 
      <button class="btn btn-primary mb-3 cookie-consent-button" data-value="true">Accept All</button>
```

instead of: 

``` html
      <a class="btn btn-accept mb-3" href="/cookies?cookies=true">ACCEPT ALL</a>
```

@Pralish section views are still broken. Could you use violet.restarone.solutions to investigate and patch?

**Comment by donrestarone** [comment]
⚠️ running temporary deployment to nikean org (https://github.com/restarone/violet_rails/settings/environments/447769648/edit) to validate watch time tracking:
https://github.com/restarone/violet_rails/actions/runs/4010531168/jobs/6960144816

**Comment by donrestarone** [comment]
video watch time tracking LGTM on nikean.org: 

Screen Shot 2023-01-30 at 1 42 59 PM

**Comment by Pralish** [comment]
### Determining the visibility threshold for section views 

Threshold indicates at what percentage of the target's visibility the tracking should be executed. 0.75 threshold indicates that the tracking is done when 75% of the section is visible in the screen.

However for larger sections, 75% of the content can never be visible. Therefore we need to adjust the threshold.

A good rule of thumb is if the section is double the screen size, adjust the threshold to slightly less than 0.5 and if the section is 4 times the screen size, adjust threshold to less than  0.25, and so on

REF:

https://stackoverflow.com/questions/66296057/intersectionobserver-does-not-work-on-small-screens-for-long-sections-js/

https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#thresholds

**Pull request merged**
