### PR TITLE
[feature] 2FA + ability to enforce 2FA in Subdomain

### PR DESCRIPTION
**Pull request by donrestarone**
Addresses: #1081 

Demo: 

https://user-images.githubusercontent.com/55496123/195891042-e9508cb0-0d07-4b1c-9e1c-f0fcfc2659a4.mov

Co-authored-by: Er. Ajay Shrestha <55496123+ajaystha42@users.noreply.github.com>
Co-authored-by: Ajay Shrestha <er.ajaystha@gmail.com>
Co-authored-by: Prashant Khadka <prashant.khadkda052@gmail.com>

### CODE REVIEW

**Comment by donrestarone** [comment]
@ajaystha42 Im seeing a couple of bugs here. I have applied the migrations on `violet-test.net` so we are now committed to shipping this feature soon. Please see https://violet-test.net for the following issues:

1. user can get locked out of entering the OTP since the OTP form is missing
Screen Shot 2022-11-10 at 9 58 45 PM

2. 1 in 4 OTP's are rejected.

**Comment by ajaystha42** [comment]
> @ajaystha42 Im seeing a couple of bugs here. I have applied the migrations on `violet-test.net` so we are now committed to shipping this feature soon. Please see https://violet-test.net for the following issues:
> 
> 1. user can get locked out of entering the OTP since the OTP form is missing
> 
> Screen Shot 2022-11-10 at 9 58 45 PM
> 
> 2. 1 in 4 OTP's are rejected.

@donrestarone  I will look on it. Also, I dont see the changes of 2fa in https://violet-test.net/ .

**Comment by ajaystha42** [comment]
> @ajaystha42 Im seeing a couple of bugs here. I have applied the migrations on `violet-test.net` so we are now committed to shipping this feature soon. Please see https://violet-test.net for the following issues:
> 
> 1. user can get locked out of entering the OTP since the OTP form is missing
> 
> Screen Shot 2022-11-10 at 9 58 45 PM
> 
> 2. 1 in 4 OTP's are rejected.

I fixed the Issue No. 1.
For Issue No, 2, it is caused due to time limit of the otp. Do you want to increase the time limit?

**Comment by donrestarone** [comment]
@ajaystha42 where is the OTP timeout set? Each code should be valid for 10 minutes

**Comment by ajaystha42** [comment]
> @ajaystha42 where is the OTP timeout set? Each code should be valid for 10 minutes

By default it is set around 30 seconds. I will update it to 10 minutes

**Comment by ajaystha42** [comment]
> @ajaystha42 where is the OTP timeout set? Each code should be valid for 10 minutes

@donrestarone  if we set the otp time out to 10 minutes? the same code can be used for multiple times and we wont be requiring to send email for every otp request, is that what we need?

**Comment by donrestarone** [comment]
@ajaystha42 no. 30 seconds is not enough time for someone to enter the OTP code. It should be something reasonable like 2-3 minutes.

**Comment by donrestarone** [comment]
@ajaystha42 still locked out from changing my password. Have you tested this flow on the review app? 
Screen Shot 2022-11-13 at 1 11 08 PM
Screen Shot 2022-11-13 at 1 11 00 PM

**Comment by ajaystha42** [comment]
> @ajaystha42 still locked out from changing my password. Have you tested this flow on the review app?
> Screen Shot 2022-11-13 at 1 11 08 PM
> Screen Shot 2022-11-13 at 1 11 00 PM

@donrestarone  Yes if the otp is invalid theres no way we can send a new otp from this screen. Do you want to redirect to edit page or put a button to resend otp if the otp is invalid?

**Comment by donrestarone** [comment]
@ajaystha42 yes, add a button to resend OTP.

**Comment by kripananda-yadav** [comment]
### Acceptance Criteria:

When the user logs in for the first time user must encounter the 2FA.
When the IP (Network of the Device) changes user must be presented with the 2FA for the login
When user goes through the password change process the user must be presented with the 2FA.
When user enters invalid Token for while authenticating with 2FA proper validation message must be displayed
When user is invited for access to a particular domain user must encounter with 2FA.
Received token must be only valid for a particular period of the time.

**Pull request merged**
