### PR TITLE
[feature] AJAX'ify API resource list view

### PR DESCRIPTION
**Pull request by Pralish**
Demo:

https://user-images.githubusercontent.com/50227291/225883851-dca39d67-f12e-4ad0-b1b1-2cd44e1e1f74.mov

### CODE REVIEW

**Comment by donrestarone** [comment]
🧪 test plan

1. acceptance criteria ✅ 
2. regression: user permissions ✅

**Comment by donrestarone** [comment]
temporary [deployment](https://github.com/restarone/violet_rails/actions/runs/4432085699/jobs/7815359759) to [nikean.org](https://github.com/restarone/violet_rails/settings/environments/447769648/edit)

**Comment by donrestarone** [comment]
@Pralish there is a server error when deleting. See review app for, 

``` txt
An ArgumentError occurred in api_namespaces#show:

  invalid value for Integer(): "null"
  app/controllers/comfy/admin/api_namespaces_controller.rb:42:in `show'



```
and

https://user-images.githubusercontent.com/35935196/226362535-78ce16d3-0f59-4575-ba44-ec2cca6d6ce2.mov

**Comment by Pralish** [comment]
> @Pralish there is a server error when deleting. See review app for,
> 
> ```
> An ArgumentError occurred in api_namespaces#show:
> 
>   invalid value for Integer(): "null"
>   app/controllers/comfy/admin/api_namespaces_controller.rb:42:in `show'
> ```
> 
> and

@donrestarone , This has been fixed

**Comment by donrestarone** [comment]
@Pralish when order is applied, and a delete is performed the order is not persisted after the deleted node is removed. 

Screen Shot 2023-03-20 at 8 37 49 PM

Screen Shot 2023-03-20 at 8 38 07 PM

after this issue is addressed by preserving the order state this PR should be good to be promoted to staging

-- delete works as expected when a filter is applied

Screen Shot 2023-03-20 at 8 40 50 PM

**Comment by Pralish** [comment]
`when order is applied, and a delete is performed the order is not persisted after the deleted node is removed.
`
@donrestarone , It's fixed

**Pull request merged**
