### PR TITLE
Rc: automate prod deployments + differentiate between JSON editor tree (read) vs view mode

### PR DESCRIPTION
**Pull request by donrestarone**

### CODE REVIEW

**Comment by donrestarone** [comment]
@Pralish JSON editor is not in view only mode:
Screen Shot 2022-03-21 at 10 27 24 PM
Screen Shot 2022-03-21 at 10 27 19 PM

**Comment by Pralish** [comment]
@donrestarone,  The feature seems to be working on my local. Is this staged on https://violet-staging.restarone.solutions/. 
If so, can you send me an invitation to access it.

**Comment by donrestarone** [comment]
@Pralish its staged at `violet.restarone.solutions`

**Comment by Pralish** [comment]
@donrestarone , looks like the deployment didn't complete properly. None of the changes are visible. 

eg, the resource page should have json editor too.
Screen Shot 2022-03-22 at 9 12 49 PM

**Comment by donrestarone** [comment]
@Pralish the issue is that for some reason merging changes to `rc` is deploying `master`

see below: 

``` bash
ubuntu@ip-172-31-68-13:/var/www/violet$ tail revisions.log 
Branch deprecateCTA (at becf5a7b298155be1a49acc353a66cb03c6d5b3e) deployed as release 20220109033555 by don
Branch deprecateCTA (at 54c7a7866bfd2e30009152200dc131dfb95066c3) deployed as release 20220116164118 by don
Branch page-preview-broken-for-apex-domain (at 562d5a3c0c0b356767aca93bad853c3fc5d84254) deployed as release 20220205200338 by don
Branch master (at 8a79823385f7c830622a922f2f81459d097588cd) deployed as release 20220301112647 by runner
Branch master (at 8a79823385f7c830622a922f2f81459d097588cd) deployed as release 20220312032739 by runner
Branch master (at bb382039c1b77c336896897cfa13e2f731d4253f) deployed as release 20220314232954 by runner
Branch master (at bb382039c1b77c336896897cfa13e2f731d4253f) deployed as release 20220314234034 by runner
Branch master (at 0ffb41ddf72183fd8a134579340ecd6bc37caeb8) deployed as release 20220315010918 by runner
Branch master (at 0ffb41ddf72183fd8a134579340ecd6bc37caeb8) deployed as release 20220322022006 by runner
Branch master (at 0ffb41ddf72183fd8a134579340ecd6bc37caeb8) deployed as release 20220322022246 by runner
```

**Comment by donrestarone** [comment]
@Pralish after merging your latest deployment automation changes, its still deploying master branch to staging. In this case, it should be deploying `rc` -- so we can test proposed changes in a release candidate on the staging environment before merging to master and making it generally available for clients.

**Comment by Pralish** [comment]
https://github.com/restarone/violet_rails/pull/333

It turned out we are setting branch like this:
https://github.com/restarone/violet_rails/blob/0ffb41ddf72183fd8a134579340ecd6bc37caeb8/config/deploy.rb#L13

@donrestarone , Please add environment variable BRANCH in the staging env. I have updated the wiki.

https://github.com/restarone/violet_rails/wiki/Blue-Green-deployment-using-a-Github-Action

**Comment by donrestarone** [comment]
@Pralish great work on this PR! This is a system that will keep evolving.

**Pull request merged**
