### PR TITLE
safe executable ERB in dynamic segments in API (#937)

### PR DESCRIPTION
**Pull request by donrestarone**
Addresses: https://github.com/restarone/violet_rails/issues/934

### Allow ERB in API Actions

Screen Shot 2022-07-19 at 12 13 53 PM

Screen Shot 2022-07-19 at 8 59 42 AM

https://user-images.githubusercontent.com/35935196/179740864-bb5a7b31-0daf-4ce2-959c-55ff673f10a1.mov

### CODE REVIEW

**Comment by donrestarone** [comment]
@Pralish this is on its way to Heroku. 

## 📋  Acceptance criteria

1. General regression pass: existing API Action stacks: HTTP / Email / Serve File/ Redirect ⌛ 
2. General regression pass: existing API Action stacks without dynamic segments  ⌛ 
3. Feature: allow ERB (`<% %>` / `<%= %>`) and interpolation (`#{}`) in HTTP action
4. Feature: allow ERB (`<% %>` / `<%= %>`) and interpolation (`#{}`) in Email action
5. Feature: allow ERB (`<% %>` / `<%= %>`) and interpolation (`#{}`) in Redirect action

**Comment by donrestarone** [comment]
@Pralish Please see below for an acceptance failure

## Feature: allow ERB (<% %> / <%= %>) and interpolation (#{}) in HTTP action ❌

Screen Shot 2022-07-19 at 8 57 54 AM

Screen Shot 2022-07-19 at 9 00 46 AM

**Comment by Pralish** [comment]
@donrestarone The acceptance failure has been addressed. Thanks

**Comment by donrestarone** [comment]
@Ayon95 can you UAT your requirement on this branch?

**Comment by Ayon95** [comment]
I've tested it by conditionally rendering links. It's working fine.

Capture
Capture2
Capture3

**Pull request merged**
