### PR TITLE
[feature] Ability to mention user in forum

### PR DESCRIPTION
**Pull request by kripananda-yadav**
Addresses: #1173 

Demo:

https://user-images.githubusercontent.com/18470532/199933805-7669b727-cd76-43ad-9125-c8be379973a6.mov

https://user-images.githubusercontent.com/18470532/200725154-1e9ce5f7-c7ed-4ec3-8b46-9c9bc232567f.mov

### CODE REVIEW

**Comment by kripananda-yadav** [comment]
### ACCEPTANCE CRITERIA

-User should be able to TAG/MENTION available user by name  or email in any  thread.
-Tagged/Mentioned user should be notified when any new comment is added in a thread.
-When user is tagged/mentioned to any thread they should be able to reply/respond to that particular thread.
-User must be able unsubscribed to any thread.
-When user Unsubscribe to any thread no further notification should be received by that user related to that particular thread.
- User who are tag/Mention in the thread should be able to Tag/Mention other new user to the thread.

**Comment by alis-khadka** [comment]
> Deployed review-app can be viewed at https://review-1256.violet-test.net

@kripananda-yadav It's ready for you to test it out.

**Comment by alis-khadka** [comment]
@Regaron 
Let's make sure to commit `lock` file changes as well.
https://github.com/restarone/violet_rails/pull/1256/commits/8037c48933e1fd61be5d815beb03b1f309e811ca

**Comment by kripananda-yadav** [comment]
image
Autosuggest option should be aligned to where the (@) symbol is started.

**Comment by kripananda-yadav** [comment]
Email Mentioning: 
When user mention a user through the Email the email is not displayed on the Comment as it disappear.

While Mentioning:
image

After Posting the Comment with Email Mentioning:

image

The Email has disappear.

**Comment by kripananda-yadav** [comment]
@Regaron Some issues has been raised. If you have any quires regarding the issue let me know.

**Comment by Regaron** [comment]
@kripananda-yadav Could you provide a video or reproduction steps for those issue? I'm unable to reproduce.
Screenshot 2022-11-30 at 9 58 21 PM

**Comment by Regaron** [comment]
@kripananda-yadav Changes have been made. Please check once again.

**Comment by donrestarone** [comment]
@kripananda-yadav @Regaron This PR is long overdue, please ensure it can be deployed ASAP

**Comment by donrestarone** [comment]
@kripananda-yadav Im wrapping up testing for this task now. Moving forward, please add the label `pending-uat-on-testnet` when you start testing and `passing-uat-on-testnet` if/when the PR is passes testing

**Comment by kripananda-yadav** [comment]
Sure @donrestarone

**Pull request merged**
