### PR TITLE
[feature] add rack timeout

### PR DESCRIPTION
**Pull request by donrestarone**
Addresses: https://github.com/restarone/violet_rails/issues/1397

Demo: 

https://user-images.githubusercontent.com/55496123/217051621-69b8e185-31e3-4288-b533-383046e7fd2e.mov

### CODE REVIEW

**Comment by donrestarone** [comment]
this is the second revision of the original PR that was passing feature testing: https://github.com/restarone/violet_rails/pull/1402

however, we discovered that this branch fails CI (due to ember app build timeout) and also has a broken CMS editor (discovered by @Sushmit1997 while working on markedrestaurant.com that was temporarily running ajaystha42bugfix/increase_max_timeouts (at c83ae70198e9b0e059cedc41ae7cf2776981187b) deployed as release 20230220201902) 


Im reopening this PR so we can fix the above 2 issues and ship again 

Screen Shot 2023-02-25 at 12 11 11 PM

**Comment by ajaystha42** [comment]
@donrestarone  This is the Editing Page view. The Content part is fixed here
Screenshot 2023-02-25 at 16 49 22

**Comment by donrestarone** [comment]
@ajaystha42 it looks ok in dev, what about in the review app (prod)?

**Comment by ajaystha42** [comment]
@donrestarone  This is from the review app:
Screenshot 2023-02-25 at 17 46 13

**Pull request merged**
